// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseInstaller() {
  return window['go']['main']['App']['CloseInstaller']();
}

export function GetInstallDir() {
  return window['go']['main']['App']['GetInstallDir']();
}

export function Install(arg1) {
  return window['go']['main']['App']['Install'](arg1);
}

export function LaunchAndClose() {
  return window['go']['main']['App']['LaunchAndClose']();
}
